import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingChatbot } from "@/components/floating-chatbot";
import { UserProvider } from "@/lib/context/user-context";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased`}
      >
        <UserProvider>
          {children}
          <FloatingChatbot />
        </UserProvider>
      </body>
    </html>
  );
}
